trigger:
- main  # 트리거할 브랜치 이름

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'sontry-azurecr-connection'  # Azure DevOps에서 설정한 서비스 연결 이름
    repository: 'sontry/model-container'  # ACR 또는 Docker Hub에 저장할 이미지 이름
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
