trigger:
- main  # 기본 브랜치 이름으로 변경

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'sontry.azurecr.io'
    repository: 'https://github.com/sontry/sontry.git'
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)